--[[

    CITO SERVER
    Initializes Cito loader with server modules.

    Encryptal 

--]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Cito = require(ReplicatedStorage.Shared:WaitForChild("Cito")).new()

Cito:Discover({ReplicatedStorage.Shared, script}) -- All descendent modules of these directories can be imported.
    :PreInit(script.Controllers)
    :Init(script.Controllers)

